version: '3'
services:
    redis:
      image: redis:alpine
      container_name: redis-queue
      command: redis-server --save 20 1 --loglevel warning
      ports:
        - 6379:6379
      restart: always
      volumes: 
        - cache:/data
volumes:
  cache:
    driver: local